spring.application.name=creditengine

spring.datasource.url=jdbc:postgresql://localhost:5432/credit_engine
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

pricing.base-rate=0.01
